"""Изменил структуру таблицы reviews

Revision ID: 69f87adb39d8
Revises: 9c49e3484a31
Create Date: 2025-05-28 21:13:24.280929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f87adb39d8'
down_revision: Union[str, None] = '9c49e3484a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('normalized_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'normalized_rating')
    # ### end Alembic commands ###
