"""add raw_rating column to reviews

Revision ID: 9c49e3484a31
Revises: bc04961bcb9e
Create Date: 2025-05-23 23:31:29.999246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c49e3484a31'
down_revision: Union[str, None] = 'bc04961bcb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('raw_rating', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'raw_rating')
    # ### end Alembic commands ###
